pub const NodeConstant = struct {
    name: [:0]const u8,
    value: i64,
};

pub const node_constants = [_]NodeConstant{
    .{ .name = "ELEMENT_NODE", .value = 1 },
    .{ .name = "ATTRIBUTE_NODE", .value = 2 },
    .{ .name = "TEXT_NODE", .value = 3 },
    .{ .name = "CDATA_SECTION_NODE", .value = 4 },
    .{ .name = "ENTITY_REFERENCE_NODE", .value = 5 },
    .{ .name = "ENTITY_NODE", .value = 6 },
    .{ .name = "PROCESSING_INSTRUCTION_NODE", .value = 7 },
    .{ .name = "COMMENT_NODE", .value = 8 },
    .{ .name = "DOCUMENT_NODE", .value = 9 },
    .{ .name = "DOCUMENT_TYPE_NODE", .value = 10 },
    .{ .name = "DOCUMENT_FRAGMENT_NODE", .value = 11 },
    .{ .name = "NOTATION_NODE", .value = 12 },
    .{ .name = "DOCUMENT_POSITION_DISCONNECTED", .value = 1 },
    .{ .name = "DOCUMENT_POSITION_PRECEDING", .value = 2 },
    .{ .name = "DOCUMENT_POSITION_FOLLOWING", .value = 4 },
    .{ .name = "DOCUMENT_POSITION_CONTAINS", .value = 8 },
    .{ .name = "DOCUMENT_POSITION_CONTAINED_BY", .value = 16 },
    .{ .name = "DOCUMENT_POSITION_IMPLEMENTATION_SPECIFIC", .value = 32 },
};

pub const html_element_constructors = [_][:0]const u8{
    "HTMLInputElement",
    "HTMLBodyElement",
    "HTMLHtmlElement",
    "HTMLHeadElement",
    "HTMLTitleElement",
    "HTMLFrameSetElement",
    "HTMLButtonElement",
    "HTMLFormElement",
    "HTMLSelectElement",
    "HTMLOptionElement",
    "HTMLTextAreaElement",
    "HTMLLabelElement",
    "HTMLAnchorElement",
    "HTMLImageElement",
    "HTMLIFrameElement",
    "HTMLTemplateElement",
    "HTMLDivElement",
    "HTMLSpanElement",
    "HTMLUnknownElement",
    "HTMLLIElement",
    "HTMLOListElement",
    "HTMLUListElement",
};

pub const form_value_constructors = [_][*:0]const u8{
    "HTMLInputElement",
    "HTMLTextAreaElement",
    "HTMLSelectElement",
};

pub const window_constructor_exports = [_][*:0]const u8{
    "Window",
    "EventTarget",
    "Node",
    "Element",
    "HTMLElement",
    "SVGElement",
    "Document",
    "XMLDocument",
    "DOMImplementation",
    "DocumentFragment",
    "DocumentType",
    "CharacterData",
    "ProcessingInstruction",
    "Text",
    "Comment",
    "HTMLInputElement",
    "HTMLBodyElement",
    "HTMLFrameSetElement",
    "HTMLButtonElement",
    "HTMLFormElement",
    "HTMLSelectElement",
    "HTMLOptionElement",
    "HTMLTextAreaElement",
    "HTMLLabelElement",
    "HTMLAnchorElement",
    "HTMLImageElement",
    "HTMLIFrameElement",
    "HTMLTemplateElement",
    "HTMLDivElement",
    "NodeList",
    "NamedNodeMap",
    "HTMLCollection",
    "Event",
    "CustomEvent",
    "MouseEvent",
    "InputEvent",
    "CompositionEvent",
    "CustomElementRegistry",
    "DOMRect",
    "MutationObserver",
    "ResizeObserver",
};
