import { GlobalRegistrator } from "zig-dom/global-registrator";

const PropertySymbol = Object.freeze({
  ownerWindow: Symbol.for("zig-dom.ownerWindow"),
  ownerDocument: Symbol.for("zig-dom.ownerDocument"),
  nodeArray: Symbol.for("zig-dom.nodeArray"),
  classList: Symbol.for("zig-dom.classList"),
});

const nativeDOM = {
  GlobalRegistrator,
  PropertySymbol,
  Window: globalThis.Window,
  Document: globalThis.Document,
  DocumentType: globalThis.DocumentType,
  DocumentFragment: globalThis.DocumentFragment,
  Node: globalThis.Node,
  Element: globalThis.Element,
  HTMLElement: globalThis.HTMLElement,
  SVGElement: globalThis.SVGElement,
  CharacterData: globalThis.CharacterData,
  Text: globalThis.Text,
  Comment: globalThis.Comment,
  NodeList: globalThis.NodeList,
  HTMLCollection: globalThis.HTMLCollection,
  EventTarget: globalThis.EventTarget,
  Event: globalThis.Event,
  CustomEvent: globalThis.CustomEvent,
  MouseEvent: globalThis.MouseEvent,
  DOMRect: globalThis.DOMRect,
  DOMException: globalThis.DOMException,
  MutationObserver: globalThis.MutationObserver,
  ResizeObserver: globalThis.ResizeObserver,
  HTMLAnchorElement: globalThis.HTMLAnchorElement || globalThis.HTMLElement,
  HTMLButtonElement: globalThis.HTMLButtonElement || globalThis.HTMLElement,
  HTMLFormElement: globalThis.HTMLFormElement || globalThis.HTMLElement,
  HTMLIFrameElement: globalThis.HTMLIFrameElement || globalThis.HTMLElement,
  HTMLInputElement: globalThis.HTMLInputElement || globalThis.HTMLElement,
  HTMLLabelElement: globalThis.HTMLLabelElement || globalThis.HTMLElement,
  HTMLLIElement: globalThis.HTMLLIElement || globalThis.HTMLElement,
  HTMLOListElement: globalThis.HTMLOListElement || globalThis.HTMLElement,
  HTMLOptionElement: globalThis.HTMLOptionElement || globalThis.HTMLElement,
  HTMLSelectElement: globalThis.HTMLSelectElement || globalThis.HTMLElement,
  HTMLTextAreaElement: globalThis.HTMLTextAreaElement || globalThis.HTMLElement,
  HTMLUListElement: globalThis.HTMLUListElement || globalThis.HTMLElement,
};

export const {
  Window,
  Document,
  DocumentType,
  DocumentFragment,
  Node,
  Element,
  HTMLElement,
  SVGElement,
  CharacterData,
  Text,
  Comment,
  NodeList,
  HTMLCollection,
  EventTarget,
  Event,
  CustomEvent,
  MouseEvent,
  DOMRect,
  DOMException,
  MutationObserver,
  ResizeObserver,
  HTMLAnchorElement,
  HTMLButtonElement,
  HTMLFormElement,
  HTMLIFrameElement,
  HTMLInputElement,
  HTMLLabelElement,
  HTMLLIElement,
  HTMLOListElement,
  HTMLOptionElement,
  HTMLSelectElement,
  HTMLTextAreaElement,
  HTMLUListElement,
} = nativeDOM;

export { GlobalRegistrator, PropertySymbol };
export default nativeDOM;
